project_id = "dgdeiybuxlabdfofzxpy"

[functions.send-rsvp-confirmation]
verify_jwt = false

[functions.send-contribution-confirmation]
verify_jwt = false

[functions.daily-analytics-aggregation]
verify_jwt = false

[functions.send-support-report]
verify_jwt = false
