name: Deploy to Firebase Hosting via Workload Identity Federation
on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci --legacy-peer-deps
      - run: npm run build

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: "projects/1017057598145/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "firebase-adminsdk-fbsvc@twisted-hearth-foundation.iam.gserviceaccount.com"
          create_credentials_file: true
          export_environment_variables: true

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: firebase-adminsdk-fbsvc@twisted-hearth-foundation.iam.gserviceaccount.com
          channelId: live
          projectId: twisted-hearth-foundation
