name: Deploy to Development

on:
  push:
    branches: 
      - v-3.0.1.1-UserDropdownViewFIX
      - v-3.0.0.0-Milestone
      - test-preview-channel
      - dev
      - develop
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy to development'
        required: true
        default: 'v-3.0.1.1-UserDropdownViewFIX'

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch || github.ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Development Site
        run: |
          firebase use twisted-hearth-foundation
          echo "🚀 Deploying to DEVELOPMENT SITE..."
          firebase deploy --only hosting:dev
          echo "✅ Development deployment complete!"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
