name: Deploy to Development

on:
  push:
    branches: [ test-preview-channel, dev, develop, v-3.0.0.0-Milestone ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy to development'
        required: true
        default: 'dev'

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch || github.ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Development Site
        run: |
          firebase use twisted-hearth-foundation
          firebase target:apply hosting dev twisted-hearth-foundation-dev
          firebase deploy --only hosting:dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
